services:
  replaybrowser-postgres:
    image: docker.io/postgres
    environment:
      POSTGRES_DB: replaybrowser
      POSTGRES_USER: replaybrowser
      POSTGRES_PASSWORD: ErFAUeWx78gpgtWUnLq8
    ports:
      - "5432:5432"
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana-enterprise
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - '3000:3000'
    restart: unless-stopped

volumes:
  grafana-storage: {}
