apiVersion: 1

datasources:
  - name: Replaybrowser Postgres
    uid: replaybrowser-postgres
    type: postgres
    access: proxy
    url: replaybrowser-postgres:5432
    database: replaybrowser
    user: replaybrowser
    isDefault: false
    editable: false

    secureJsonData:
      password: "ErFAUeWx78gpgtWUnLq8"

    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
